# Generated by Django 5.1.7 on 2025-03-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='is_Finished',
            new_name='is_finished',
        ),
    ]
