# Generated by Django 5.1.7 on 2025-05-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_post_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='community',
        ),
        migrations.AddField(
            model_name='post',
            name='community_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
