# Generated by Django 5.1.7 on 2025-05-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_post_community_post_community_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='post',
        ),
        migrations.AddField(
            model_name='solution',
            name='community_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
