# Generated by Django 5.1.7 on 2025-03-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_homework_due_date_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
