# Generated by Django 5.1.7 on 2025-05-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_solution_post_solution_community_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='community_id',
            new_name='solution_id',
        ),
    ]
