# Generated by Django 5.1.7 on 2025-05-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_community_id_solution_solution_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='solution_id',
            new_name='post_id',
        ),
    ]
