# Generated by Django 5.1.7 on 2025-05-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_solution_id_solution_post_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
